name: Django CD
on:
  release:
    types: [published,edited]
  
jobs:
  build_and_push_image:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: awsbreathpanda/drfsite/drfsite
          tag_with_ref: true
